---
- block:
    - name: docker_ce_key
      remote_user: ubuntu
      apt_key: 
             url: https://download.docker.com/linux/ubuntu/gpg
             state: present 
    - name: docker_repo
      apt_repository:
                    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
                    state: present 
                    filename: docker_ce
    - name: docker_ce_install
      apt:
         update_cache: yes
         name: docker-ce
  become: yes
