---
- name : docker_ce_dep
  apt: >
     name: {{ item }} 
     state: present 
     update_cache: yes
  with_items:
      - apt-transports-https
      - ca-certificates
      - curl
      - software-properties-common
- import_tasks: docker_ce_install.yml

#pt-transport-https \
#    ca-certificates \
#    curl \
#    software-properties-common
