baseURL = "http://172.17.0.2/"
languageCode = "en-us"
title = "gespo"
theme = "hugo-theme-nix"


[menu]
  [[menu.header]]
    name = "this_site"
    weight = 0
    url = "https://github.com/gabrielhesposito/personal_website"
  [[menu.header]]
    name = "resume"
    weight = 1
    url = "/docs/resume.pdf"


[params]
  GithubID = "gabrielhesposito"
  #LinkedInID = "your_linkedin"
  Name = "gespo"
  HeaderUsername = "gitusername"
  HeaderHostname = "github"
  Email = "gitusernameplusgithub@gmail.com"
  About = "No CSS/HTML skills  →  GNU/Linux Engineer ~~~~~ Debian at home, CentOS at work ~~~~~"
  ProfilePicture = "/pics/profile_pic.png"


