baseURL = "http://gespo.me/"
languageCode = "en-us"
title = "gespo"
theme = "hugo-theme-nix"


[menu]
  [[menu.header]]
    name = "this_site"
    weight = 0
    url = "https://github.com/gabrielhesposito/personal_website"
  [[menu.header]]
    name = "resume"
    weight = 1
    url = "/docs/resume.pdf"


[params]
  GithubID = "gabrielhesposito"
  LinkedInID = "gespodotme"
  Name = "gespo"
  HeaderUsername = "gabrielhesposito"
  HeaderHostname = "github"
  Email = "gitusernameplusgithub@gmail.com"
  About = "Hi, I am a passionate  GNU/Linux Engineer. This site is not just a portfolio, it is also an OS automation project focusing on AWS / Docker Security / golang and SaaS monitoring solutions. Email me!"
  ProfilePicture = "/pics/profile_pic.png"


