baseURL = "http://172.17.0.3/"
languageCode = "en-us"
title = "gespo"
theme = "hugo-theme-nix"


[menu]
  [[menu.header]]
    name = "resume"
    weight = 1
    url = "/resume"


[params]
  GithubID = "gabrielhesposito"
  #LinkedInID = "your_linkedin"
  Name = "gespo"
  HeaderUsername = "gitusername"
  HeaderHostname = "github"
  Email = "gitusernameplusgithub@gmail.com"
  About = "Debian at home, CentOS at work"
  ProfilePicture = "pics/profile_pic.png"


