version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/personal_website
    environment:
      HUGO_DIR: site_root
    steps:

      # install git
      - run: sudo apt-get install git

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            sudo apt-get install -y  python3-pip python3-dev build-essential 
            pip3 install awscli

      # build with Hugo
      - run: HUGO_ENV=production hugo -v --source $HUGO_DIR -d $HUGO_DIR/public

      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              cd $HUGO_DIR && hugo deploy
            else
              echo "Not master branch, dry run only"
            fi 
