#docker pull cibuilds/hugo:0.157.0
version: '2.1'
orbs:
  hugo: circleci/hugo@1.4.0
jobs:
  deploySite:
    docker:
      - image: hugomods/hugo:debian-reg-exts-0.154.5
    steps:
      - attach_workspace:
          at: site_root
      - run: hugo version && hugo deploy
  deployResume:
    docker:
      - image: hugomods/hugo:debian-reg-exts-0.154.5
    steps:
      - attach_workspace:
          at: site_root
      - run: hugo version && hugo deploy


workflows:
  master:
    jobs:
      - hugo/build:
          name: site
          html-proofer: false
          source: site_root/
          version: 0.154.5 
      - hugo/build:
          name: resume
          html-proofer: false
          source: resume/
          version: 0.154.5
      - deploySite:
          filters:
            branches:
              only: fix-deploy
          requires:
            - site