#docker pull cibuilds/hugo:0.157.0
version: '2.1'
orbs:
  hugo: cibuilds/hugo:0.158.0
jobs:
  deploy:
    docker:
      - image: cimg/base
    steps:
      - attach_workspace:
          at: my-site
      - run: hugo deploy
test:
  docker:
      - image: cimg/base
    steps:
      - attach_workspace:
          at: my-site
      - run: hugo deploy
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          source: site_root/
          version: 0.141.0
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build