#docker pull cibuilds/hugo:0.157.0
version: '2.1'
orbs:
  hugo: circleci/hugo@1.4.0

jobs:
  deploySite:
    docker:
      - image: hugomods/hugo:ci-0.154.5
    steps:
      - checkout:
          path: repo/
      - attach_workspace:
          at: repo/site_root/
      - run: 'hugo version'
      - run: 'ls -la repo/site_root/*'
      - run: 
          command: HUGO_ENVIRONMENT=production hugo deploy
          working_directory: repo/site_root/

  deployResume:
    docker:
      - image: hugomods/hugo:ci-0.154.5
    steps:
      - checkout:
          path: repo/
      - attach_workspace:
          at: repo/resume/
      - run: 'hugo version'
      - run: 'ls -la repo/resume/*'
      - run: 
          command: HUGO_ENVIRONMENT=production hugo deploy
          working_directory: repo/resume/

workflows:
  master:
    jobs:
      - hugo/build:
          name: site
          html-proofer: false
          source: site_root/
          version: 0.154.5
          hugo-env: production
          persist-to-workspace: true        # ← tell the orb to persist
          destination: site_root_public/

      - hugo/build:
          name: resume
          html-proofer: false
          source: resume/
          version: 0.154.5
          persist-to-workspace: true        # ← tell the orb to persist
          destination: resume_public/resume/
          hugo-env: production
      

      - deploySite:
          filters:
            branches:
              only: fix-persist-paths
          requires:
            - site

      - deployResume:
          filters:
            branches:
              only: fix-persist-paths
          requires:
            - resume
            - deploySite