---
- block:
    - name: dump_services
      command: service --status-all
    - name : update_apt
      register: result
      apt: 
         update_cache: yes 
    - name : remove_docker
      apt:
         name: docker.io
         state: absent
         purge: yes
         autoremove: yes
         autoclean: yes 
  become: yes
